#MySQL Connection!
MySQL:
  Host: ' '
  User: ' '
  Password: ' '
  Database: ' '
  Port: 3306
  Use: false

#Default Path plugins/MySQLAPI
SQLite:
  Path: 'plugins/MySQLAPI'
  FileName: 'database'
  Use: false